# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image with uv pre-installed
# https://github.com/smithery-ai/reference-servers/blob/main/src/git/Dockerfile
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS uv

# Install the project into `/app`
WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Add the project source code
ADD . /app

# Create virtual environment and install the project with its dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv --python 3.12 && \
    . .venv/bin/activate && \
    uv pip install -e .

FROM python:3.12-slim-bookworm

WORKDIR /app

COPY --from=uv /app/.venv /app/.venv
COPY --from=uv /app /app

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8080

# Default: stdio (for local use / Claude Desktop).
ENTRYPOINT ["mcp-paradex"]
CMD []
